
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always

    ports:
      - "5672:5672"   # conexão da aplicação
      - "15672:15672" # painel web

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: